### ISSUE TITLE
[Bugfix] 로그아웃이 안 됨

### ISSUE THREAD

**Issue by Matilda0730** [Happiness-Meta/final-front#37]
## (페이지)

`const [cookies, removeCookie] = useCookies(["email", "nickname", "token"])`
 
`const removeCookies = () => {
    removeCookie("email");
    removeCookie("nickname");
    removeCookie("token");
  }; `

- [ ] 이게 React에서는 되는데 Next.js에서는 안 된다. 서버 사이드 렌더링과 충돌하기 때문이라는 것 같은데, 해결 방안을 찾아보아야 할 것 같다.

**Comment by Matilda0730** [comment]
`const [cookies, setCookie, removeCookie] = useCookies(["email", "nickname", "token"]);`

setCookie를 추가했더니 갑자기 해결됐다...

**Comment by HermannChoi** [comment]
제가 정리해 놓은 거 안 읽어보신 거 같은데, 읽어보시는 걸 추천합니다. 사용하지 않는 setCookie를 그냥 넣으면 build할 때 오류가 뜨겠죠?
